#
# Your Crowdin credentials
#
"project_id" : "491811"
"api_token" : "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiJ3UUVxdmhVM3ZMT2EyWGljbVV5VCIsImp0aSI6IjdmZjVjNTFkZjAwYTFiMjA2MmY4MTkyODk5MmJiN2NiODcyZjRkMWU1NjM5YTQwZWJhZjhiNzcyOTdmMzU3OWFhZDA2ZjU5ODVmNGEwMzdjIiwiaWF0IjoxNjc5MDg2ODgyLjM2OTMyNywibmJmIjoxNjc5MDg2ODgyLjM2OTMzMiwiZXhwIjoxNjgxNjc4ODgyLjI2NjMwNiwic3ViIjoiMTQ4MjQ4NzIiLCJzY29wZXMiOlsicHJvamVjdCJdLCJkb21haW4iOm51bGwsImFzc29jaWF0aW9ucyI6WyIqIl0sInNlc3Npb24iOjB9.pBfswDCD0UnB1GVJmgFHf6etD4ptaBLblyTfZPFY3jTlCDvci1hlrrq98iLbeeJpd2g90U4_R9TO90bTcRTzPXQH_7DettyE4zL_cBRro7KJk93oqdlr8t10ouwYkKj9J5ROMNnxjZMm3WR7PtG0xERzLQ3FmMD4IQkjkCsmCR4qD-lQK0FmY_NbpA8WPR5x4hbAPClOygiLaFChB1Du3snpXYHXPOmn-vkG_wJxYNI47thHsqRuU7UtMBFrpf6vA1LCerQhIc93pOfnM5eq3XZs5alAEhaR6BuSdVYFGIyrGRnlz_NEBLXfisk_sqjyhMz1hzHmDAvl_IfGQFt7rggGgX_Smhp5Dmqr_tPjfWfycUW64cGp5Jqcag1Zxw1xX-ksPpOY14IuRX6T6ThfsQxATumMcb0z0sLj_92P83n0YCm0I7q6WSGHdrkHvXtCaY39eL0uTN1Ps2BizMnfqH9faG-XJVlDoOLNr9aRjvVz1mGjP0BSQ4EfKXRIIjvuyrmpQM3TTo0IrfTBfmCJn0bfs7hnBfxBRk9F2nOOuyPzpIvn8KEaxbq0Hz21Br2Zpa-hq6wsP_lpiYdnEf-eEDEfyMQpOw-u9a1qexB1-BiB75TLUOOESYMf6ULIHsRMcU3SjbVhQcmHNGZFB_wZNL6wTazTmc_8TjuK3wKpgxI"
"base_path" : "Sources/OversizeLocalizable/Localize"
"base_url" : "https://api.crowdin.com"
"preserve_hierarchy": true
files: [
 {
  "source" : "/en.lproj/Localizable.strings",
  "translation" : "/%two_letters_code%_%original_file_name%",
 }
]
