name: Localize
on:
  push:
    branches:
      - main
jobs:

  synchronize-with-crowdin:
    name: Crowdin sync
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Crowdin action
        uses: crowdin/github-action@v1
        with:
          upload_sources: true
          upload_translations: true
          download_translations: true
          localization_branch_name: l10n_crowdin_translations
          create_pull_request: true
          pull_request_title: 'New Crowdin Translations'
          pull_request_body: 'New Crowdin translations by [Crowdin GH Action](https://github.com/crowdin/github-action)'
          pull_request_base_branch_name: 'main'
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

  swift_format:
    name: swift-format
    runs-on: macOS-11
    steps:
      - uses: actions/checkout@v2
      - name: Xcode Select
        run: sudo xcode-select -s /Applications/Xcode_14.2.app
      - name: Install
        run: brew install swiftgen
      - name: Generate
        run: swiftgen
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Run swiftgen
          branch: 'main'
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}

